name: Python Package using Conda

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        random-id: [1, 2, 3, 4, 5]  # Thêm các giá trị ngẫu nhiên cho công việc

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: conda env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

    - name: Random Job 1
      if: matrix.random-id == 1
      run: |
        echo "Running Random Job 1"
        # Thêm lệnh thực hiện công việc của bạn ở đây

    - name: Random Job 2
      if: matrix.random-id == 2
      run: |
        echo "Running Random Job 2"
        # Thêm lệnh thực hiện công việc của bạn ở đây

    - name: Random Job 3
      if: matrix.random-id == 3
      run: |
        echo "Running Random Job 3"
        # Thêm lệnh thực hiện công việc của bạn ở đây

    - name: Random Job 4
      if: matrix.random-id == 4
      run: |
        echo "Running Random Job 4"
        # Thêm lệnh thực hiện công việc của bạn ở đây

    - name: Random Job 5
      if: matrix.random-id == 5
      run: |
        echo "Running Random Job 5"
        # Thêm lệnh thực hiện công việc của bạn ở đây
